In [1]:
from pathlib import Path
import pandas as pd
import re

In [2]:
FOCAL_DIR = Path(
    "/Users/catherinexie/Documents/Grad Application /Mock Project/UN General Debate Corpus/TXT/Focal Corpus"
)

DEV_DIR = Path(
    "/Users/catherinexie/Documents/Grad Application /Mock Project/UN General Debate Corpus/TXT/Development Corpus"
)

In [3]:
print("Focal folder exists:", FOCAL_DIR.exists())
print("Development folder exists:", DEV_DIR.exists())

Focal folder exists: True
Development folder exists: True

In [4]:
focal_files = sorted(FOCAL_DIR.rglob("*.txt"))
dev_files = sorted(DEV_DIR.rglob("*.txt"))

print("Focal TXT files:", len(focal_files))
print("Development TXT files:", len(dev_files))

Focal TXT files: 180
Development TXT files: 1755

In [5]:
for f in focal_files[:20]:
    print(f.name)

CHL_71_2016.txt
CHL_72_2017.txt
CHL_73_2018.txt
CHL_74_2019.txt
CHL_75_2020.txt
CHL_76_2021.txt
CHL_77_2022.txt
CHL_78_2023.txt
CHL_79_2024.txt
CHL_80_2025.txt
CHN_71_2016.txt
CHN_72_2017.txt
CHN_73_2018.txt
CHN_74_2019.txt
CHN_75_2020.txt
CHN_76_2021.txt
CHN_77_2022.txt
CHN_78_2023.txt
CHN_79_2024.txt
CHN_80_2025.txt

In [6]:
for f in dev_files[:20]:
    print(f)

/Users/catherinexie/Documents/Grad Application /Mock Project/UN General Debate Corpus/TXT/Development Corpus/Session 71 - 2016/AFG_71_2016.txt
/Users/catherinexie/Documents/Grad Application /Mock Project/UN General Debate Corpus/TXT/Development Corpus/Session 71 - 2016/AGO_71_2016.txt
/Users/catherinexie/Documents/Grad Application /Mock Project/UN General Debate Corpus/TXT/Development Corpus/Session 71 - 2016/ALB_71_2016.txt
/Users/catherinexie/Documents/Grad Application /Mock Project/UN General Debate Corpus/TXT/Development Corpus/Session 71 - 2016/AND_71_2016.txt
/Users/catherinexie/Documents/Grad Application /Mock Project/UN General Debate Corpus/TXT/Development Corpus/Session 71 - 2016/ARE_71_2016.txt
/Users/catherinexie/Documents/Grad Application /Mock Project/UN General Debate Corpus/TXT/Development Corpus/Session 71 - 2016/ARG_71_2016.txt
/Users/catherinexie/Documents/Grad Application /Mock Project/UN General Debate Corpus/TXT/Development Corpus/Session 71 - 2016/ARM_71_2016.txt
/Users/catherinexie/Documents/Grad Application /Mock Project/UN General Debate Corpus/TXT/Development Corpus/Session 71 - 2016/ATG_71_2016.txt
/Users/catherinexie/Documents/Grad Application /Mock Project/UN General Debate Corpus/TXT/Development Corpus/Session 71 - 2016/AUS_71_2016.txt
/Users/catherinexie/Documents/Grad Application /Mock Project/UN General Debate Corpus/TXT/Development Corpus/Session 71 - 2016/AUT_71_2016.txt
/Users/catherinexie/Documents/Grad Application /Mock Project/UN General Debate Corpus/TXT/Development Corpus/Session 71 - 2016/AZE_71_2016.txt
/Users/catherinexie/Documents/Grad Application /Mock Project/UN General Debate Corpus/TXT/Development Corpus/Session 71 - 2016/BDI_71_2016.txt
/Users/catherinexie/Documents/Grad Application /Mock Project/UN General Debate Corpus/TXT/Development Corpus/Session 71 - 2016/BEL_71_2016.txt
/Users/catherinexie/Documents/Grad Application /Mock Project/UN General Debate Corpus/TXT/Development Corpus/Session 71 - 2016/BEN_71_2016.txt
/Users/catherinexie/Documents/Grad Application /Mock Project/UN General Debate Corpus/TXT/Development Corpus/Session 71 - 2016/BFA_71_2016.txt
/Users/catherinexie/Documents/Grad Application /Mock Project/UN General Debate Corpus/TXT/Development Corpus/Session 71 - 2016/BGD_71_2016.txt
/Users/catherinexie/Documents/Grad Application /Mock Project/UN General Debate Corpus/TXT/Development Corpus/Session 71 - 2016/BGR_71_2016.txt
/Users/catherinexie/Documents/Grad Application /Mock Project/UN General Debate Corpus/TXT/Development Corpus/Session 71 - 2016/BHR_71_2016.txt
/Users/catherinexie/Documents/Grad Application /Mock Project/UN General Debate Corpus/TXT/Development Corpus/Session 71 - 2016/BHS_71_2016.txt
/Users/catherinexie/Documents/Grad Application /Mock Project/UN General Debate Corpus/TXT/Development Corpus/Session 71 - 2016/BIH_71_2016.txt

In [7]:
def parse_speech_file(filepath, corpus_type):
    """
    Parse a UN General Debate speech file named like:
    AFG_71_2016.txt

    Returns one dictionary representing one speech.
    """

    stem = filepath.stem
    parts = stem.split("_")

    if len(parts) != 3:
        raise ValueError(f"Unexpected filename format: {filepath.name}")

    iso3 = parts[0]
    session = int(parts[1])
    year = int(parts[2])

    text = filepath.read_text(
        encoding="utf-8",
        errors="replace"
    )

    return {
        "corpus": corpus_type,
        "iso3": iso3,
        "session": session,
        "year": year,
        "filename": filepath.name,
        "filepath": str(filepath),
        "text": text,
        "word_count": len(text.split())
    }

In [8]:
focal_files = sorted(FOCAL_DIR.rglob("*.txt"))
dev_files = sorted(DEV_DIR.rglob("*.txt"))

In [9]:
focal_records = [
    parse_speech_file(f, "focal")
    for f in focal_files
]

focal_df = pd.DataFrame(focal_records)

In [10]:
focal_df.head()

,corpus,iso3,session,year,filename,filepath,text,word_count
0,focal,CHL,71,2016,CHL_71_2016.txt,/Users/catherinexie/Documents/Grad Application...,We are living in times that show us the necess...,1300
1,focal,CHL,72,2017,CHL_72_2017.txt,/Users/catherinexie/Documents/Grad Application...,I want to begin by sending a fraternal greetin...,2553
2,focal,CHL,73,2018,CHL_73_2018.txt,/Users/catherinexie/Documents/Grad Application...,"Twenty years ago, in this very Hall, Kofi Anna...",4375
3,focal,CHL,74,2019,CHL_74_2019.txt,/Users/catherinexie/Documents/Grad Application...,Every generation faces its own challenges but ...,2726
4,focal,CHL,75,2020,CHL_75_2020.txt,/Users/catherinexie/Documents/Grad Application...,Mr. President of the United Nations General As...,3092

In [11]:
dev_records = [
    parse_speech_file(f, "development")
    for f in dev_files
]

dev_df = pd.DataFrame(dev_records)

In [12]:
dev_df.head()

,corpus,iso3,session,year,filename,filepath,text,word_count
0,development,AFG,71,2016,AFG_71_2016.txt,/Users/catherinexie/Documents/Grad Application...,It is my distinct pleasure to attend the seven...,2904
1,development,AGO,71,2016,AGO_71_2016.txt,/Users/catherinexie/Documents/Grad Application...,It is a great honour to speak on behalf of the...,1467
2,development,ALB,71,2016,ALB_71_2016.txt,/Users/catherinexie/Documents/Grad Application...,"It is a special pleasure for me, in my capacit...",2021
3,development,AND,71,2016,AND_71_2016.txt,/Users/catherinexie/Documents/Grad Application...,"This year, once again, the United Nations call...",2791
4,development,ARE,71,2016,ARE_71_2016.txt,/Users/catherinexie/Documents/Grad Application...,"At the outset, I am pleased to congratulate Hi...",2079

In [13]:
print("Focal dataframe shape:", focal_df.shape)
print("Development dataframe shape:", dev_df.shape)

Focal dataframe shape: (180, 8)
Development dataframe shape: (1755, 8)

In [14]:
FOCAL_ISO3 = [
    "USA", "GBR",
    "CHN", "JPN",
    "SAU", "JOR",
    "COL", "CHL",
    "IND", "PAK",
    "GHA", "KEN",
    "IDN", "THA",
    "KAZ", "TJK",
    "POL", "ROU"
]

In [15]:
print(sorted(focal_df["iso3"].unique()))

['CHL', 'CHN', 'COL', 'GBR', 'GHA', 'IDN', 'IND', 'JOR', 'JPN', 'KAZ', 'KEN', 'PAK', 'POL', 'ROU', 'SAU', 'THA', 'TJK', 'USA']

In [16]:
print(sorted(FOCAL_ISO3))

['CHL', 'CHN', 'COL', 'GBR', 'GHA', 'IDN', 'IND', 'JOR', 'JPN', 'KAZ', 'KEN', 'PAK', 'POL', 'ROU', 'SAU', 'THA', 'TJK', 'USA']

In [17]:
set(focal_df["iso3"].unique()) == set(FOCAL_ISO3)

True

In [18]:
focal_counts = (
    focal_df
    .groupby("iso3")
    .size()
    .sort_index()
)

print(focal_counts)

iso3
CHL    10
CHN    10
COL    10
GBR    10
GHA    10
IDN    10
IND    10
JOR    10
JPN    10
KAZ    10
KEN    10
PAK    10
POL    10
ROU    10
SAU    10
THA    10
TJK    10
USA    10
dtype: int64

In [19]:
(focal_counts == 10).all()

np.True_

In [20]:
coverage = pd.crosstab(
    focal_df["iso3"],
    focal_df["year"]
)

coverage

year  2016  2017  2018  2019  2020  2021  2022  2023  2024  2025
iso3
CHL      1     1     1     1     1     1     1     1     1     1
CHN      1     1     1     1     1     1     1     1     1     1
COL      1     1     1     1     1     1     1     1     1     1
GBR      1     1     1     1     1     1     1     1     1     1
GHA      1     1     1     1     1     1     1     1     1     1
IDN      1     1     1     1     1     1     1     1     1     1
IND      1     1     1     1     1     1     1     1     1     1
JOR      1     1     1     1     1     1     1     1     1     1
JPN      1     1     1     1     1     1     1     1     1     1
KAZ      1     1     1     1     1     1     1     1     1     1
KEN      1     1     1     1     1     1     1     1     1     1
PAK      1     1     1     1     1     1     1     1     1     1
POL      1     1     1     1     1     1     1     1     1     1
ROU      1     1     1     1     1     1     1     1     1     1
SAU      1     1     1     1     1     1     1     1     1     1
THA      1     1     1     1     1     1     1     1     1     1
TJK      1     1     1     1     1     1     1     1     1     1
USA      1     1     1     1     1     1     1     1     1     1

In [21]:
expected_years = list(range(2016, 2026))

correct_year_columns = (
    sorted(coverage.columns.tolist()) == expected_years
)

all_one_per_year = (
    coverage.reindex(columns=expected_years, fill_value=0) == 1
).all().all()

print("Correct years present:", correct_year_columns)
print("Exactly one speech per country per year:", all_one_per_year)

Correct years present: True
Exactly one speech per country per year: True

In [22]:
overlap = sorted(
    set(dev_df["iso3"]) &
    set(FOCAL_ISO3)
)

print("Focal countries still found in development corpus:", overlap)

Focal countries still found in development corpus: []

In [23]:
print(sorted(dev_df["year"].unique()))

[np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025)]

In [24]:
focal_duplicates = (
    focal_df
    .groupby(["iso3", "year"])
    .size()
    .reset_index(name="n")
)

focal_duplicates[
    focal_duplicates["n"] != 1
]

Empty DataFrame
Columns: [iso3, year, n]
Index: []

In [25]:
dev_duplicates = (
    dev_df
    .groupby(["iso3", "year"])
    .size()
    .reset_index(name="n")
)

dev_duplicates[
    dev_duplicates["n"] > 1
].head(20)

Empty DataFrame
Columns: [iso3, year, n]
Index: []

In [26]:
print(
    "Empty focal speeches:",
    (focal_df["text"].str.strip() == "").sum()
)

print(
    "Empty development speeches:",
    (dev_df["text"].str.strip() == "").sum()
)

Empty focal speeches: 0
Empty development speeches: 0

In [27]:
focal_df["word_count"].describe()

count     180.000000
mean     2171.383333
std       951.973952
min       611.000000
25%      1554.000000
50%      1978.500000
75%      2571.750000
max      8242.000000
Name: word_count, dtype: float64

In [28]:
focal_df[
    ["iso3", "year", "filename", "word_count"]
].sort_values(
    "word_count"
).head(20)

    iso3  year         filename  word_count
55   IDN  2021  IDN_76_2021.txt         611
74   JOR  2020  JOR_75_2020.txt         738
75   JOR  2021  JOR_76_2021.txt         903
54   IDN  2020  IDN_75_2020.txt         950
174  USA  2020  USA_75_2020.txt         981
141  SAU  2017  SAU_72_2017.txt         999
73   JOR  2019  JOR_74_2019.txt        1010
133  ROU  2019  ROU_74_2019.txt        1036
135  ROU  2021  ROU_76_2021.txt        1084
131  ROU  2017  ROU_72_2017.txt        1117
56   IDN  2022  IDN_77_2022.txt        1119
76   JOR  2022  JOR_77_2022.txt        1128
136  ROU  2022  ROU_77_2022.txt        1131
137  ROU  2023  ROU_78_2023.txt        1143
138  ROU  2024  ROU_79_2024.txt        1172
145  SAU  2021  SAU_76_2021.txt        1183
77   JOR  2023  JOR_78_2023.txt        1202
57   IDN  2023  IDN_78_2023.txt        1203
63   IND  2019  IND_74_2019.txt        1209
132  ROU  2018  ROU_73_2018.txt        1219

In [29]:
dev_df[
    ["iso3", "year", "filename", "word_count"]
].sort_values(
    "word_count"
).head(20)

     iso3  year         filename  word_count
13    BEN  2016  BEN_71_2016.txt         463
945   GNB  2021  GNB_76_2021.txt         480
1017  RWA  2021  RWA_76_2021.txt         492
447   LTU  2018  LTU_73_2018.txt         508
269   LTU  2017  LTU_72_2017.txt         537
757   ERI  2020  ERI_75_2020.txt         540
311   RWA  2017  RWA_72_2017.txt         540
752   DNK  2020  DNK_75_2020.txt         603
667   RWA  2019  RWA_74_2019.txt         611
216   CZE  2017  CZE_72_2017.txt         636
842   RWA  2020  RWA_75_2020.txt         638
882   ZMB  2020  ZMB_75_2020.txt         679
1193  RWA  2022  RWA_77_2022.txt         679
779   HUN  2020  HUN_75_2020.txt         681
133   RWA  2016  RWA_71_2016.txt         682
1489  KOR  2024  KOR_79_2024.txt         729
1322  LBY  2023  LBY_78_2023.txt         730
1121  GNB  2022  GNB_77_2022.txt         730
581   ERI  2019  ERI_74_2019.txt         739
91    LTU  2016  LTU_71_2016.txt         739

In [30]:
FOCAL_METADATA = {
    "USA": ("United States", "Modern West"),
    "GBR": ("United Kingdom", "Modern West"),

    "CHN": ("China", "East Asia"),
    "JPN": ("Japan", "East Asia"),

    "SAU": ("Saudi Arabia", "Arab region"),
    "JOR": ("Jordan", "Arab region"),

    "COL": ("Colombia", "Latin America"),
    "CHL": ("Chile", "Latin America"),

    "IND": ("India", "South Asia"),
    "PAK": ("Pakistan", "South Asia"),

    "GHA": ("Ghana", "Sub-Saharan Africa"),
    "KEN": ("Kenya", "Sub-Saharan Africa"),

    "IDN": ("Indonesia", "Southeast Asia"),
    "THA": ("Thailand", "Southeast Asia"),

    "KAZ": ("Kazakhstan", "Central Asia"),
    "TJK": ("Tajikistan", "Central Asia"),

    "POL": ("Poland", "Eastern Europe"),
    "ROU": ("Romania", "Eastern Europe")
}

In [31]:
focal_df["country"] = focal_df["iso3"].map(
    lambda x: FOCAL_METADATA[x][0]
)

focal_df["region"] = focal_df["iso3"].map(
    lambda x: FOCAL_METADATA[x][1]
)

In [32]:
focal_df[
    ["iso3", "country", "region", "year"]
].head(20)

   iso3 country         region  year
0   CHL   Chile  Latin America  2016
1   CHL   Chile  Latin America  2017
2   CHL   Chile  Latin America  2018
3   CHL   Chile  Latin America  2019
4   CHL   Chile  Latin America  2020
5   CHL   Chile  Latin America  2021
6   CHL   Chile  Latin America  2022
7   CHL   Chile  Latin America  2023
8   CHL   Chile  Latin America  2024
9   CHL   Chile  Latin America  2025
10  CHN   China      East Asia  2016
11  CHN   China      East Asia  2017
12  CHN   China      East Asia  2018
13  CHN   China      East Asia  2019
14  CHN   China      East Asia  2020
15  CHN   China      East Asia  2021
16  CHN   China      East Asia  2022
17  CHN   China      East Asia  2023
18  CHN   China      East Asia  2024
19  CHN   China      East Asia  2025

In [33]:
PROJECT_ROOT = Path.cwd().parent
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

print(PROCESSED_DIR)
print("Processed folder exists:", PROCESSED_DIR.exists())

/Users/catherinexie/Documents/kgl-mockproject/data/processed
Processed folder exists: True

In [34]:
focal_df.to_csv(
    PROCESSED_DIR / "focal_2016_2025.csv",
    index=False
)

dev_df.to_csv(
    PROCESSED_DIR / "development_2016_2025.csv",
    index=False
)