# 04 — Self-Assertion KGL Expansion

This notebook performs FastText-based synonym expansion and concept expansion
for the frozen Self-Assertion Seed Set v1.

No purification is performed in this notebook.

In [5]:
from pathlib import Path

import pandas as pd
import numpy as np
import gensim.downloader as api

In [6]:
PROJECT_ROOT = Path("..")

SEED_FILE = (
    PROJECT_ROOT
    / "data"
    / "seed_candidates"
    / "self_assertion_seed_set_v1.csv"
)

OUTPUT_DIR = (
    PROJECT_ROOT
    / "data"
    / "expansion"
)

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

In [2]:
from pathlib import Path

print("Current working directory:")
print(Path.cwd())

Current working directory:
/Users/catherinexie/Documents/kgl-mockproject/notebooks

In [3]:
PROJECT_ROOT = Path("..")

SEED_FILE = (
    PROJECT_ROOT
    / "data"
    / "seed_candidates"
    / "self_assertion_seed_set_v1.csv"
)

OUTPUT_DIR = (
    PROJECT_ROOT
    / "data"
    / "expansion"
)

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print("Project root:", PROJECT_ROOT.resolve())
print("Seed file exists:", SEED_FILE.exists())
print("Output directory exists:", OUTPUT_DIR.exists())

Project root: /Users/catherinexie/Documents/kgl-mockproject
Seed file exists: True
Output directory exists: True

In [7]:
seed_df = pd.read_csv(SEED_FILE)

print("Number of frozen seeds:", len(seed_df))
print(seed_df["seed"].tolist())

Number of frozen seeds: 14
['urge', 'propose', 'reject', 'advocate', 'reaffirm', 'insist', 'declare', 'resist', 'assert', 'defend', 'self-assertion', 'intend', 'ready', 'exercise']

In [8]:
print(seed_df)

              seed                     facet     source final_decision
0             urge           advance_outcome   original           keep
1          propose           advance_outcome   original           keep
2           reject         resist_constraint   original           keep
3         advocate           advance_outcome   original           keep
4         reaffirm         maintain_position   original           keep
5           insist         maintain_position   original           keep
6          declare            claim_position   original           keep
7           resist         resist_constraint   original           keep
8           assert            claim_position   original  theory_anchor
9           defend      defend_self_relevant   original  theory_anchor
10  self-assertion           construct_label   original  theory_anchor
11          intend    commit_intended_action  gap_added           keep
12           ready    commit_intended_action  gap_added           keep
13        exercise  exercise_capability_role  gap_added  theory_anchor

In [9]:
MODEL_NAME = "fasttext-wiki-news-subwords-300"

ft = api.load(MODEL_NAME)

[==================================================] 100.0% 958.5/958.4MB downloaded

In [10]:
print(type(ft))
print("Vector dimensions:", ft.vector_size)

<class 'gensim.models.keyedvectors.KeyedVectors'>
Vector dimensions: 300

In [11]:
seed_vector_check = []

for seed in seed_df["seed"]:
    try:
        vec = ft.get_vector(seed)
        available = True
        norm = np.linalg.norm(vec)
    except KeyError:
        available = False
        norm = np.nan

    seed_vector_check.append({
        "seed": seed,
        "vector_available": available,
        "vector_norm": norm
    })

seed_vector_check = pd.DataFrame(seed_vector_check)

seed_vector_check

              seed  vector_available  vector_norm
0             urge              True     1.288498
1          propose              True     0.800554
2           reject              True     0.966094
3         advocate              True     0.788096
4         reaffirm              True     0.884402
5           insist              True     0.845252
6          declare              True     0.838490
7           resist              True     0.989003
8           assert              True     0.873927
9           defend              True     0.968208
10  self-assertion              True     0.502082
11          intend              True     0.921630
12           ready              True     1.058329
13        exercise              True     0.764934

In [12]:
seed_vector_check["vector_available"].value_counts()

vector_available
True    14
Name: count, dtype: int64

In [13]:
seed_vectors = {}

for seed in seed_df["seed"]:
    vec = ft.get_vector(seed)
    vec = vec / np.linalg.norm(vec)
    seed_vectors[seed] = vec

In [14]:
for seed in list(seed_vectors.keys())[:5]:
    print(seed, np.linalg.norm(seed_vectors[seed]))

urge 1.0
propose 1.0
reject 1.0
advocate 1.0
reaffirm 1.0

In [15]:
SYNONYM_THRESHOLD = 0.75
CONCEPT_THRESHOLD = 0.45

In [16]:
def synonym_expand(
    model,
    seeds,
    similarity_threshold=0.75,
    topn=500
):
    rows = []

    for seed in seeds:
        neighbors = model.most_similar(
            positive=[seed],
            topn=topn
        )

        for word, similarity in neighbors:
            if similarity >= similarity_threshold:
                rows.append({
                    "seed": seed,
                    "expanded_term": word,
                    "similarity": similarity,
                    "expansion_type": "synonym"
                })

    return pd.DataFrame(rows)

In [17]:
synonym_expansion = synonym_expand(
    model=ft,
    seeds=seed_df["seed"].tolist(),
    similarity_threshold=SYNONYM_THRESHOLD,
    topn=500
)

print("Total synonym-expansion rows:", len(synonym_expansion))

synonym_expansion.head(30)

Total synonym-expansion rows: 51

        seed    expanded_term  similarity expansion_type
0       urge           urging    0.790209        synonym
1       urge            urges    0.789152        synonym
2       urge            urged    0.775632        synonym
3       urge          implore    0.773136        synonym
4    propose        proposing    0.818100        synonym
5    propose       re-propose    0.805075        synonym
6    propose        repropose    0.797981        synonym
7    propose          suggest    0.783833        synonym
8    propose  counter-propose    0.781766        synonym
9    propose         proposes    0.777562        synonym
10   propose         proposed    0.769956        synonym
11    reject         rejected    0.802450        synonym
12    reject           accept    0.800865        synonym
13    reject          rejects    0.798281        synonym
14    reject        rejecting    0.793222        synonym
15  advocate        advocates    0.831214        synonym
16  advocate       advocating    0.795685        synonym
17  advocate       advocation    0.761888        synonym
18  advocate        advocated    0.761289        synonym
19  advocate        advocator    0.756424        synonym
20  advocate    self-advocate    0.750883        synonym
21  reaffirm           affirm    0.823465        synonym
22  reaffirm        re-affirm    0.820965        synonym
23  reaffirm      reaffirming    0.784433        synonym
24  reaffirm        reaffirms    0.782236        synonym
25  reaffirm        reconfirm    0.774019        synonym
26  reaffirm       reaffirmed    0.772455        synonym
27  reaffirm        reiterate    0.765178        synonym
28    insist        insisting    0.813037        synonym
29    insist         insisted    0.755750        synonym

In [18]:
synonym_counts = (
    synonym_expansion
    .groupby("seed")
    .size()
    .reset_index(name="n_expanded_terms")
    .sort_values(
        "n_expanded_terms",
        ascending=False
    )
)

synonym_counts

              seed  n_expanded_terms
7          propose                 7
8         reaffirm                 7
0         advocate                 6
4         exercise                 5
1           assert                 4
2          declare                 4
9           reject                 4
12            urge                 4
5           insist                 3
6           intend                 2
10          resist                 2
11  self-assertion                 2
3           defend                 1

In [19]:
pd.set_option("display.max_rows", 200)

synonym_expansion.sort_values(
    ["seed", "similarity"],
    ascending=[True, False]
)

              seed       expanded_term  similarity expansion_type
15        advocate           advocates    0.831214        synonym
16        advocate          advocating    0.795685        synonym
17        advocate          advocation    0.761888        synonym
18        advocate           advocated    0.761289        synonym
19        advocate           advocator    0.756424        synonym
20        advocate       self-advocate    0.750883        synonym
37          assert           asserting    0.779048        synonym
38          assert           re-assert    0.756543        synonym
39          assert               claim    0.753320        synonym
40          assert            reassert    0.751403        synonym
31         declare            declared    0.824428        synonym
32         declare           declaring    0.792193        synonym
33         declare            proclaim    0.783124        synonym
34         declare            declares    0.767281        synonym
41          defend           defending    0.769944        synonym
46        exercise        non-exercise    0.826314        synonym
47        exercise           excercise    0.823893        synonym
48        exercise           exercises    0.810040        synonym
49        exercise          exercising    0.809452        synonym
50        exercise            exercize    0.807466        synonym
28          insist           insisting    0.813037        synonym
29          insist            insisted    0.755750        synonym
30          insist             insists    0.754826        synonym
44          intend           intending    0.761712        synonym
45          intend             intends    0.760988        synonym
4          propose           proposing    0.818100        synonym
5          propose          re-propose    0.805075        synonym
6          propose           repropose    0.797981        synonym
7          propose             suggest    0.783833        synonym
8          propose     counter-propose    0.781766        synonym
9          propose            proposes    0.777562        synonym
10         propose            proposed    0.769956        synonym
21        reaffirm              affirm    0.823465        synonym
22        reaffirm           re-affirm    0.820965        synonym
23        reaffirm         reaffirming    0.784433        synonym
24        reaffirm           reaffirms    0.782236        synonym
25        reaffirm           reconfirm    0.774019        synonym
26        reaffirm          reaffirmed    0.772455        synonym
27        reaffirm           reiterate    0.765178        synonym
11          reject            rejected    0.802450        synonym
12          reject              accept    0.800865        synonym
13          reject             rejects    0.798281        synonym
14          reject           rejecting    0.793222        synonym
35          resist           resisting    0.807128        synonym
36          resist             resists    0.764469        synonym
42  self-assertion  self-assertiveness    0.812192        synonym
43  self-assertion      self-assertive    0.791159        synonym
0             urge              urging    0.790209        synonym
1             urge               urges    0.789152        synonym
2             urge               urged    0.775632        synonym
3             urge             implore    0.773136        synonym

In [20]:
expanded_seeds = set(synonym_expansion["seed"])

zero_synonym_seeds = [
    seed
    for seed in seed_df["seed"]
    if seed not in expanded_seeds
]

print("Seeds with zero synonym expansions above .75:")
print(zero_synonym_seeds)

Seeds with zero synonym expansions above .75:
['ready']

In [21]:
SYNONYM_FILE = (
    OUTPUT_DIR
    / "self_assertion_synonym_expansion_primary.csv"
)

synonym_expansion.to_csv(
    SYNONYM_FILE,
    index=False
)

print(SYNONYM_FILE)

../data/expansion/self_assertion_synonym_expansion_primary.csv

In [22]:
seed_matrix = np.vstack(
    [
        seed_vectors[seed]
        for seed in seed_df["seed"]
    ]
)

concept_centroid = seed_matrix.mean(axis=0)

concept_centroid = (
    concept_centroid
    / np.linalg.norm(concept_centroid)
)

print("Centroid dimensions:", concept_centroid.shape)
print("Centroid norm:", np.linalg.norm(concept_centroid))

Centroid dimensions: (300,)
Centroid norm: 1.0

In [23]:
CONCEPT_THRESHOLD = 0.45
CONCEPT_TOPN = 10000

In [24]:
concept_neighbors = ft.similar_by_vector(
    concept_centroid,
    topn=CONCEPT_TOPN
)

In [25]:
concept_expansion = pd.DataFrame(
    concept_neighbors,
    columns=["expanded_term", "similarity"]
)

concept_expansion = concept_expansion[
    concept_expansion["similarity"] >= CONCEPT_THRESHOLD
].copy()

concept_expansion["expansion_type"] = "concept"

concept_expansion = (
    concept_expansion
    .sort_values(
        "similarity",
        ascending=False
    )
    .reset_index(drop=True)
)

concept_expansion

      expanded_term  similarity expansion_type
0            assert    0.797689        concept
1              urge    0.789836        concept
2            reject    0.781349        concept
3           propose    0.774361        concept
4            defend    0.772548        concept
...             ...         ...            ...
9995        survive    0.557673        concept
9996    soliloquize    0.557673        concept
9997  carte-blanche    0.557669        concept
9998   clarfication    0.557664        concept
9999      discussio    0.557662        concept

[10000 rows x 3 columns]

In [26]:
lowest_returned_similarity = concept_neighbors[-1][1]

print(
    "Similarity of the 10,000th nearest term:",
    lowest_returned_similarity
)

Similarity of the 10,000th nearest term: 0.5576624870300293

In [29]:
CONCEPT_TOPN = 100000

concept_neighbors = ft.similar_by_vector(
    concept_centroid,
    topn=CONCEPT_TOPN
)

In [32]:
lowest_returned_similarity = concept_neighbors[-1][1]

print(
    "Similarity of the 100,000th nearest term:",
    lowest_returned_similarity
)

Similarity of the 100,000th nearest term: 0.4218613803386688

In [33]:
CONCEPT_THRESHOLD = 0.45

concept_expansion = pd.DataFrame(
    concept_neighbors,
    columns=["expanded_term", "similarity"]
)

concept_expansion = concept_expansion[
    concept_expansion["similarity"] >= CONCEPT_THRESHOLD
].copy()

concept_expansion["expansion_type"] = "concept"

concept_expansion = (
    concept_expansion
    .sort_values(
        "similarity",
        ascending=False
    )
    .reset_index(drop=True)
)

In [34]:
print(
    "Number of concept-expanded terms:",
    len(concept_expansion)
)

Number of concept-expanded terms: 69110

In [35]:
concept_expansion.head(50)

      expanded_term  similarity expansion_type
0            assert    0.797689        concept
1              urge    0.789836        concept
2            reject    0.781349        concept
3           propose    0.774361        concept
4            defend    0.772548        concept
5           declare    0.770948        concept
6          denounce    0.769357        concept
7           compell    0.763614        concept
8         temporize    0.763041        concept
9   counter-propose    0.761597        concept
10           insist    0.757708        concept
11        re-assert    0.755364        concept
12           accept    0.754770        concept
13           jusify    0.752917        concept
14    counter-argue    0.750730        concept
15          endorse    0.750462        concept
16             deny    0.749805        concept
17             seek    0.749134        concept
18          acccept    0.748560        concept
19          suggest    0.748500        concept
20            argue    0.748471        concept
21          concede    0.748365        concept
22           intend    0.745243        concept
23      perseverate    0.745200        concept
24           claify    0.743660        concept
25            agree    0.743524        concept
26        recognize    0.742737        concept
27         supppose    0.742716        concept
28      acknowledge    0.742473        concept
29        actualise    0.742012        concept
30         chastize    0.741343        concept
31        temporise    0.741053        concept
32         consider    0.740946        concept
33           affirm    0.739281        concept
34         reassert    0.737257        concept
35        dis-agree    0.736971        concept
36        encourage    0.736458        concept
37        re-affirm    0.735956        concept
38         renounce    0.735712        concept
39      remonstrate    0.735293        concept
40         proclaim    0.735014        concept
41          conlude    0.734842        concept
42        repropose    0.734807        concept
43           resist    0.734627        concept
44      officialize    0.732493        concept
45         advocate    0.732446        concept
46          embrace    0.732163        concept
47      demonstrate    0.731196        concept
48          contend    0.730917        concept
49          disgard    0.730712        concept

In [36]:
concept_expansion.tail(20)

          expanded_term  similarity expansion_type
69090        notices---    0.450014        concept
69091  cold-shouldering    0.450014        concept
69092        Islamicate    0.450014        concept
69093      head-turning    0.450014        concept
69094            repito    0.450013        concept
69095            go-tos    0.450013        concept
69096       slack-jawed    0.450012        concept
69097          up-field    0.450011        concept
69098             samay    0.450011        concept
69099          examples    0.450010        concept
69100       wrist-watch    0.450009        concept
69101       GMO-related    0.450008        concept
69102            weiter    0.450008        concept
69103           done--I    0.450006        concept
69104         plainness    0.450004        concept
69105         imageleft    0.450004        concept
69106    neocreationist    0.450003        concept
69107           mestres    0.450002        concept
69108      non-striking    0.450001        concept
69109          mocktail    0.450000        concept

In [37]:
CONCEPT_FILE = (
    OUTPUT_DIR
    / "self_assertion_concept_expansion_primary.csv"
)

concept_expansion.to_csv(
    CONCEPT_FILE,
    index=False
)

print(CONCEPT_FILE)

../data/expansion/self_assertion_concept_expansion_primary.csv

In [38]:
raw_seed_matrix = np.vstack(
    [
        ft.get_vector(seed)
        for seed in seed_df["seed"]
    ]
)

raw_concept_centroid = raw_seed_matrix.mean(axis=0)

print("Centroid dimensions:", raw_concept_centroid.shape)
print("Centroid norm:", np.linalg.norm(raw_concept_centroid))

Centroid dimensions: (300,)
Centroid norm: 0.6557597

In [39]:
raw_centroid_neighbors = ft.similar_by_vector(
    raw_concept_centroid,
    topn=100000
)

In [40]:
print(
    "Similarity of the 100,000th nearest term:",
    raw_centroid_neighbors[-1][1]
)

Similarity of the 100,000th nearest term: 0.41644158959388733

In [41]:
for threshold in [0.40, 0.45, 0.50]:
    n = sum(
        similarity >= threshold
        for _, similarity in raw_centroid_neighbors
    )
    
    print(
        f"Threshold {threshold:.2f}: {n:,} terms"
    )

Threshold 0.40: 100,000 terms
Threshold 0.45: 63,791 terms
Threshold 0.50: 28,572 terms

In [42]:
for threshold in [0.55, 0.60, 0.65, 0.70]:
    n = sum(
        similarity >= threshold
        for _, similarity in raw_centroid_neighbors
    )
    
    print(
        f"Threshold {threshold:.2f}: {n:,} terms"
    )

Threshold 0.55: 10,713 terms
Threshold 0.60: 3,435 terms
Threshold 0.65: 841 terms
Threshold 0.70: 146 terms

In [43]:
def show_terms_above_threshold(
    neighbors,
    threshold,
    n_show=50
):
    filtered = [
        (word, sim)
        for word, sim in neighbors
        if sim >= threshold
    ]
    
    print(
        f"Threshold {threshold:.2f}: "
        f"{len(filtered):,} terms"
    )
    
    return pd.DataFrame(
        filtered[:n_show],
        columns=["term", "similarity"]
    )

In [44]:
show_terms_above_threshold(
    raw_centroid_neighbors,
    0.45
)

Threshold 0.45: 63,791 terms

               term  similarity
0              urge    0.807748
1            assert    0.787626
2            reject    0.785834
3           propose    0.777625
4            defend    0.775598
5          denounce    0.772007
6           declare    0.768392
7           compell    0.767535
8         temporize    0.764389
9            accept    0.758967
10  counter-propose    0.758351
11           insist    0.757563
12             seek    0.756544
13           jusify    0.754024
14             deny    0.752708
15          endorse    0.751626
16          suggest    0.749872
17           intend    0.749591
18            agree    0.748582
19          concede    0.748387
20          acccept    0.748229
21        re-assert    0.745448
22    counter-argue    0.744925
23            argue    0.744752
24        encourage    0.744218
25           claify    0.743683
26        recognize    0.743065
27      acknowledge    0.742356
28           resist    0.741992
29      perseverate    0.741308
30         consider    0.741285
31         chastize    0.740418
32        temporise    0.739079
33         supppose    0.738727
34          implore    0.736598
35           affirm    0.736414
36        dis-agree    0.735052
37        repropose    0.734409
38      remonstrate    0.734038
39         renounce    0.733682
40        actualise    0.733572
41           oppose    0.733144
42        re-affirm    0.732507
43          embrace    0.732462
44          condemn    0.731973
45          approve    0.731013
46        criticize    0.730780
47          conlude    0.730591
48           advise    0.729989
49          agreeed    0.729757

In [45]:
show_terms_above_threshold(
    raw_centroid_neighbors,
    0.55
)

Threshold 0.55: 10,713 terms

               term  similarity
0              urge    0.807748
1            assert    0.787626
2            reject    0.785834
3           propose    0.777625
4            defend    0.775598
5          denounce    0.772007
6           declare    0.768392
7           compell    0.767535
8         temporize    0.764389
9            accept    0.758967
10  counter-propose    0.758351
11           insist    0.757563
12             seek    0.756544
13           jusify    0.754024
14             deny    0.752708
15          endorse    0.751626
16          suggest    0.749872
17           intend    0.749591
18            agree    0.748582
19          concede    0.748387
20          acccept    0.748229
21        re-assert    0.745448
22    counter-argue    0.744925
23            argue    0.744752
24        encourage    0.744218
25           claify    0.743683
26        recognize    0.743065
27      acknowledge    0.742356
28           resist    0.741992
29      perseverate    0.741308
30         consider    0.741285
31         chastize    0.740418
32        temporise    0.739079
33         supppose    0.738727
34          implore    0.736598
35           affirm    0.736414
36        dis-agree    0.735052
37        repropose    0.734409
38      remonstrate    0.734038
39         renounce    0.733682
40        actualise    0.733572
41           oppose    0.733144
42        re-affirm    0.732507
43          embrace    0.732462
44          condemn    0.731973
45          approve    0.731013
46        criticize    0.730780
47          conlude    0.730591
48           advise    0.729989
49          agreeed    0.729757

In [46]:
show_terms_above_threshold(
    raw_centroid_neighbors,
    0.60
)

Threshold 0.60: 3,435 terms

               term  similarity
0              urge    0.807748
1            assert    0.787626
2            reject    0.785834
3           propose    0.777625
4            defend    0.775598
5          denounce    0.772007
6           declare    0.768392
7           compell    0.767535
8         temporize    0.764389
9            accept    0.758967
10  counter-propose    0.758351
11           insist    0.757563
12             seek    0.756544
13           jusify    0.754024
14             deny    0.752708
15          endorse    0.751626
16          suggest    0.749872
17           intend    0.749591
18            agree    0.748582
19          concede    0.748387
20          acccept    0.748229
21        re-assert    0.745448
22    counter-argue    0.744925
23            argue    0.744752
24        encourage    0.744218
25           claify    0.743683
26        recognize    0.743065
27      acknowledge    0.742356
28           resist    0.741992
29      perseverate    0.741308
30         consider    0.741285
31         chastize    0.740418
32        temporise    0.739079
33         supppose    0.738727
34          implore    0.736598
35           affirm    0.736414
36        dis-agree    0.735052
37        repropose    0.734409
38      remonstrate    0.734038
39         renounce    0.733682
40        actualise    0.733572
41           oppose    0.733144
42        re-affirm    0.732507
43          embrace    0.732462
44          condemn    0.731973
45          approve    0.731013
46        criticize    0.730780
47          conlude    0.730591
48           advise    0.729989
49          agreeed    0.729757

In [47]:
show_terms_above_threshold(
    raw_centroid_neighbors,
    0.65
)

Threshold 0.65: 841 terms

               term  similarity
0              urge    0.807748
1            assert    0.787626
2            reject    0.785834
3           propose    0.777625
4            defend    0.775598
5          denounce    0.772007
6           declare    0.768392
7           compell    0.767535
8         temporize    0.764389
9            accept    0.758967
10  counter-propose    0.758351
11           insist    0.757563
12             seek    0.756544
13           jusify    0.754024
14             deny    0.752708
15          endorse    0.751626
16          suggest    0.749872
17           intend    0.749591
18            agree    0.748582
19          concede    0.748387
20          acccept    0.748229
21        re-assert    0.745448
22    counter-argue    0.744925
23            argue    0.744752
24        encourage    0.744218
25           claify    0.743683
26        recognize    0.743065
27      acknowledge    0.742356
28           resist    0.741992
29      perseverate    0.741308
30         consider    0.741285
31         chastize    0.740418
32        temporise    0.739079
33         supppose    0.738727
34          implore    0.736598
35           affirm    0.736414
36        dis-agree    0.735052
37        repropose    0.734409
38      remonstrate    0.734038
39         renounce    0.733682
40        actualise    0.733572
41           oppose    0.733144
42        re-affirm    0.732507
43          embrace    0.732462
44          condemn    0.731973
45          approve    0.731013
46        criticize    0.730780
47          conlude    0.730591
48           advise    0.729989
49          agreeed    0.729757

In [48]:
def show_bottom_terms_above_threshold(
    neighbors,
    threshold,
    n_show=20
):
    filtered = [
        (word, sim)
        for word, sim in neighbors
        if sim >= threshold
    ]
    
    return pd.DataFrame(
        filtered[-n_show:],
        columns=["term", "similarity"]
    )

In [49]:
show_bottom_terms_above_threshold(
    raw_centroid_neighbors,
    0.60
)

                term  similarity
0               soom    0.600257
1           misspeak    0.600246
2          strugling    0.600234
3             agreee    0.600228
4              chack    0.600219
5            dispell    0.600218
6              reast    0.600199
7      contridicting    0.600197
8           certaint    0.600179
9        invitiation    0.600179
10         principle    0.600170
11         brutalise    0.600160
12         confiable    0.600144
13           reraise    0.600132
14       commiserate    0.600101
15             chave    0.600062
16          actially    0.600052
17        preferring    0.600046
18  court-sanctioned    0.600041
19            mander    0.600017

In [50]:
show_bottom_terms_above_threshold(
    raw_centroid_neighbors,
    0.65,
    n_show=50
)

             term  similarity
0       expection    0.651922
1      acknowlege    0.651873
2           abase    0.651838
3       denegrate    0.651794
4          negate    0.651768
5   individualise    0.651752
6          rewite    0.651682
7      re-collect    0.651677
8         suppose    0.651634
9         mortify    0.651630
10      appricate    0.651603
11         strate    0.651543
12        scarify    0.651484
13   substantiate    0.651449
14     re-present    0.651437
15      forcefull    0.651404
16           warn    0.651387
17    re-acquaint    0.651339
18        decided    0.651333
19   over-correct    0.651328
20        damnest    0.651318
21        examine    0.651271
22     presuppose    0.651249
23     endorsment    0.651215
24        forsake    0.651182
25        express    0.651177
26        you-and    0.651158
27     immmediate    0.650852
28       resurect    0.650823
29        forbore    0.650775
30           seel    0.650770
31     appericate    0.650683
32        accept.    0.650666
33       clarrify    0.650656
34         fixate    0.650655
35      persevere    0.650599
36         excuse    0.650565
37         behove    0.650486
38       politick    0.650444
39     villainize    0.650358
40     propitiate    0.650310
41  pre-negotiate    0.650300
42   pre-announce    0.650284
43     re-instate    0.650246
44  reinvestigate    0.650198
45        actuate    0.650105
46       hold-off    0.650092
47         couuld    0.650073
48     reperesent    0.650048
49      patronize    0.650001

In [51]:
show_bottom_terms_above_threshold(
    raw_centroid_neighbors,
    0.70,
    n_show=50
)

               term  similarity
0        minimalize    0.713155
1           expouse    0.713013
2             admit    0.712357
3            agress    0.711505
4          re-claim    0.711379
5        minimalise    0.710698
6            submit    0.710528
7           support    0.709948
8            pursue    0.709723
9         disaprove    0.709386
10          folllow    0.709164
11           expect    0.708964
12         arrogate    0.708726
13         re-prove    0.708630
14       comrpomise    0.708466
15     essentialize    0.708387
16         continue    0.708292
17         re-state    0.708179
18          promote    0.707747
19         disserve    0.707699
20          indorse    0.707347
21          asssume    0.706750
22          reprove    0.706414
23          intreat    0.705820
24              use    0.705745
25             want    0.705619
26      misconceive    0.705524
27     universalize    0.705418
28    re-articulate    0.704947
29             find    0.704899
30     re-authorize    0.704746
31     legitimatize    0.704335
32        assertain    0.703822
33        help--and    0.703815
34        disinvite    0.703805
35         asserter    0.703802
36           uphold    0.703743
37         validate    0.703736
38        criticise    0.703664
39  instrumentalize    0.703333
40          prepare    0.703310
41           assume    0.702207
42         critcise    0.701512
43           do-and    0.701179
44       re-inforce    0.700931
45      re-vitalize    0.700870
46            decry    0.700384
47           invoke    0.700262
48      countermand    0.700081
49       re-embrace    0.700030

In [52]:
concept_070 = pd.DataFrame(
    [
        (word, similarity)
        for word, similarity in raw_centroid_neighbors
        if similarity >= 0.70
    ],
    columns=["expanded_term", "similarity"]
)

pd.set_option("display.max_rows", 200)

concept_070

       expanded_term  similarity
0               urge    0.807748
1             assert    0.787626
2             reject    0.785834
3            propose    0.777625
4             defend    0.775598
5           denounce    0.772007
6            declare    0.768392
7            compell    0.767535
8          temporize    0.764389
9             accept    0.758967
10   counter-propose    0.758351
11            insist    0.757563
12              seek    0.756544
13            jusify    0.754024
14              deny    0.752708
15           endorse    0.751626
16           suggest    0.749872
17            intend    0.749591
18             agree    0.748582
19           concede    0.748387
20           acccept    0.748229
21         re-assert    0.745448
22     counter-argue    0.744925
23             argue    0.744752
24         encourage    0.744218
25            claify    0.743683
26         recognize    0.743065
27       acknowledge    0.742356
28            resist    0.741992
29       perseverate    0.741308
30          consider    0.741285
31          chastize    0.740418
32         temporise    0.739079
33          supppose    0.738727
34           implore    0.736598
35            affirm    0.736414
36         dis-agree    0.735052
37         repropose    0.734409
38       remonstrate    0.734038
39          renounce    0.733682
40         actualise    0.733572
41            oppose    0.733144
42         re-affirm    0.732507
43           embrace    0.732462
44           condemn    0.731973
45           approve    0.731013
46         criticize    0.730780
47           conlude    0.730591
48            advise    0.729989
49           agreeed    0.729757
50       officialize    0.729355
51          reassert    0.729111
52        reitterate    0.728715
53           contend    0.728689
54           disgard    0.728174
55          advocate    0.727856
56         recommend    0.727740
57          proclaim    0.727423
58          critcize    0.727154
59       demonstrate    0.726815
60         re-assure    0.725589
61            decide    0.725295
62         re-commit    0.724951
63         emphasize    0.724805
64        dissaprove    0.724184
65           conceed    0.723342
66        recommmend    0.722559
67             reate    0.722146
68                do    0.721730
69           justify    0.721484
70        reconceive    0.721457
71         out-argue    0.721435
72           presume    0.721144
73           invlove    0.720762
74            infere    0.720021
75          sugggest    0.719625
76        re-instill    0.719584
77          intermit    0.718838
78        re-propose    0.718131
79           repeate    0.718124
80             exect    0.717668
81         dogmatize    0.717124
82            appply    0.717074
83        controvert    0.716928
84         reiterate    0.716741
85           pretend    0.716398
86          reaffirm    0.716018
87            appose    0.715358
88            reqire    0.715255
89         repudiate    0.715183
90          re-argue    0.715127
91      counterargue    0.715117
92           calrify    0.714450
93        re-iterate    0.714153
94          moralize    0.713990
95           chooose    0.713265
96        minimalize    0.713155
97           expouse    0.713013
98             admit    0.712357
99            agress    0.711505
100         re-claim    0.711379
101       minimalise    0.710698
102           submit    0.710528
103          support    0.709948
104           pursue    0.709723
105        disaprove    0.709386
106          folllow    0.709164
107           expect    0.708964
108         arrogate    0.708726
109         re-prove    0.708630
110       comrpomise    0.708466
111     essentialize    0.708387
112         continue    0.708292
113         re-state    0.708179
114          promote    0.707747
115         disserve    0.707699
116          indorse    0.707347
117          asssume    0.706750
118          reprove    0.706414
119          intreat    0.705820
120              use    0.705745
121             want    0.705619
122      misconceive    0.705524
123     universalize    0.705418
124    re-articulate    0.704947
125             find    0.704899
126     re-authorize    0.704746
127     legitimatize    0.704335
128        assertain    0.703822
129        help--and    0.703815
130        disinvite    0.703805
131         asserter    0.703802
132           uphold    0.703743
133         validate    0.703736
134        criticise    0.703664
135  instrumentalize    0.703333
136          prepare    0.703310
137           assume    0.702207
138         critcise    0.701512
139           do-and    0.701179
140       re-inforce    0.700931
141      re-vitalize    0.700870
142            decry    0.700384
143           invoke    0.700262
144      countermand    0.700081
145       re-embrace    0.700030

In [53]:
CONCEPT_THRESHOLD = 0.45

concept_expansion = pd.DataFrame(
    raw_centroid_neighbors,
    columns=["expanded_term", "similarity"]
)

concept_expansion = concept_expansion[
    concept_expansion["similarity"] >= CONCEPT_THRESHOLD
].copy()

concept_expansion["expansion_type"] = "concept"

concept_expansion = (
    concept_expansion
    .sort_values("similarity", ascending=False)
    .reset_index(drop=True)
)

print("Raw concept-expansion terms:", len(concept_expansion))

Raw concept-expansion terms: 63791

In [54]:
CONCEPT_FILE = (
    OUTPUT_DIR
    / "self_assertion_concept_expansion_primary.csv"
)

concept_expansion.to_csv(
    CONCEPT_FILE,
    index=False
)

print(CONCEPT_FILE)

../data/expansion/self_assertion_concept_expansion_primary.csv

In [55]:
seed_rows = pd.DataFrame({
    "term": seed_df["seed"],
    "weight": 1.0,
    "source": "seed"
})

seed_rows.head()

       term  weight source
0      urge     1.0   seed
1   propose     1.0   seed
2    reject     1.0   seed
3  advocate     1.0   seed
4  reaffirm     1.0   seed

In [56]:
synonym_rows = synonym_expansion.rename(
    columns={
        "expanded_term": "term",
        "similarity": "weight"
    }
)[["term", "weight", "seed"]].copy()

synonym_rows["source"] = (
    "synonym:" + synonym_rows["seed"].astype(str)
)

synonym_rows = synonym_rows[
    ["term", "weight", "source"]
]

synonym_rows.head()

        term    weight           source
0     urging  0.790209     synonym:urge
1      urges  0.789152     synonym:urge
2      urged  0.775632     synonym:urge
3    implore  0.773136     synonym:urge
4  proposing  0.818100  synonym:propose

In [57]:
concept_rows = concept_expansion.rename(
    columns={
        "expanded_term": "term",
        "similarity": "weight"
    }
)[["term", "weight"]].copy()

concept_rows["source"] = "concept"

concept_rows.head()

      term    weight   source
0     urge  0.807748  concept
1   assert  0.787626  concept
2   reject  0.785834  concept
3  propose  0.777625  concept
4   defend  0.775598  concept

In [58]:
raw_long = pd.concat(
    [
        seed_rows,
        synonym_rows,
        concept_rows
    ],
    ignore_index=True
)

print("Total rows before resolving duplicates:", len(raw_long))

raw_long.head()

Total rows before resolving duplicates: 63856

       term  weight source
0      urge     1.0   seed
1   propose     1.0   seed
2    reject     1.0   seed
3  advocate     1.0   seed
4  reaffirm     1.0   seed

In [59]:
raw_union = (
    raw_long
    .groupby("term", as_index=False)
    .agg(
        weight=("weight", "max"),
        sources=(
            "source",
            lambda x: "; ".join(sorted(set(x)))
        )
    )
)

In [60]:
raw_union = raw_union.sort_values(
    ["weight", "term"],
    ascending=[False, True]
).reset_index(drop=True)

In [61]:
print(
    "Unique terms in raw expanded lexicon:",
    len(raw_union)
)

raw_union.head(30)

Unique terms in raw expanded lexicon: 63791

                  term    weight                          sources
0             advocate  1.000000                    concept; seed
1               assert  1.000000                    concept; seed
2              declare  1.000000                    concept; seed
3               defend  1.000000                    concept; seed
4             exercise  1.000000                    concept; seed
5               insist  1.000000                    concept; seed
6               intend  1.000000                    concept; seed
7              propose  1.000000                    concept; seed
8                ready  1.000000                    concept; seed
9             reaffirm  1.000000                    concept; seed
10              reject  1.000000                    concept; seed
11              resist  1.000000                    concept; seed
12      self-assertion  1.000000                    concept; seed
13                urge  1.000000                    concept; seed
14           advocates  0.831214        concept; synonym:advocate
15        non-exercise  0.826314        concept; synonym:exercise
16            declared  0.824428         concept; synonym:declare
17           excercise  0.823893        concept; synonym:exercise
18              affirm  0.823465        concept; synonym:reaffirm
19           re-affirm  0.820965        concept; synonym:reaffirm
20           proposing  0.818100         concept; synonym:propose
21           insisting  0.813037          concept; synonym:insist
22  self-assertiveness  0.812192  concept; synonym:self-assertion
23           exercises  0.810040        concept; synonym:exercise
24          exercising  0.809452        concept; synonym:exercise
25            exercize  0.807466        concept; synonym:exercise
26           resisting  0.807128          concept; synonym:resist
27          re-propose  0.805075         concept; synonym:propose
28            rejected  0.802450          concept; synonym:reject
29              accept  0.800865          concept; synonym:reject

In [62]:
check_terms = [
    "assert",
    "urge",
    "ready",
    "accept",
    "implore",
    "self-assertion"
]

raw_union[
    raw_union["term"].isin(check_terms)
]

              term    weight                  sources
1           assert  1.000000            concept; seed
8            ready  1.000000            concept; seed
12  self-assertion  1.000000            concept; seed
13            urge  1.000000            concept; seed
29          accept  0.800865  concept; synonym:reject
47         implore  0.773136    concept; synonym:urge

In [63]:
RAW_EXPANDED_FILE = (
    OUTPUT_DIR
    / "self_assertion_expanded_raw_primary.csv"
)

raw_union.to_csv(
    RAW_EXPANDED_FILE,
    index=False
)

print(RAW_EXPANDED_FILE)

../data/expansion/self_assertion_expanded_raw_primary.csv